version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    # Удалены проброшенные порты
    networks:
      - common_network
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "http://elasticsearch:9200"  # Используем имя сервиса как хост
    # Оставляем порт 5044, так как он может быть нужен для приема логов
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
      - /tmp/logs/nginx/:/var/log/nginx/:ro
    command: logstash -f /config/logstash.conf
    networks:
      - common_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Используем имя сервиса как хост
    # Удален проброшенный порт
    networks:
      - common_network

volumes:
  esdata:

networks:
  common_network:
    driver: bridge
